apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosialmedia-deployment
spec:
  selector:
    matchLabels:
      app: sosialmedia
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: sosialmedia
        tier: frontend
    spec:
      containers:
      - name: sosialmedia
        image: yusufluai/apache:v2 
        ports:
          - name: sosialmedia
            containerPort: 80
        env:
          - name:  DB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  sosialmedia-mysql-secret
                key:  mysql_root_password
          - name:  DB_USER
            valueFrom:
              secretKeyRef:
                name:  sosialmedia-mysql-secret
                key:  mysql_user
          - name:  DB_PASS
            valueFrom:
              secretKeyRef:
                name:  sosialmedia-mysql-secret
                key:  mysql_user_password
          - name:  DB_NAME
            valueFrom:
              secretKeyRef:
                name:  sosialmedia-mysql-secret
                key:  mysql_db
          - name:  DB_HOST
            valueFrom:
              configMapKeyRef:
                name: sosialmedia-configmap
                key: database_url

---
kind: Service
apiVersion: v1
metadata:
  name: sosialmedia-service
spec:
  selector:
    app: sosialmedia
    tier: frontend
  type: LoadBalancer
  ports:
  - name: sosialmedia
    port:  80
    targetPort: 80
    protocol: TCP
    # nodePort: 30018